# aa: null
amp: true
batch_size: 32
bench_labeler: false
channels_last: false
clip_grad: 10.0
# color_jitter: 0.4
cooldown_epochs: 10
dataset: fashion
decay_epochs: 30
decay_rate: 0.1
distributed: false
dist_bn: ''
epochs: 200
eval_metric: map
fill_color: null
initial_checkpoint: ''
interpolation: ''
jit_loss: null
legacy_focal: null
local_rank: 0
log_interval: 50
lr: 0.01
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
model: tf_efficientdet_d0
model_ema: true
model_ema_decay: 0.9998
momentum: 0.9
native_amp: true
no_prefetcher: false
no_pretrained_backbone: false
no_resume_opt: false
opt: momentum
opt_eps: 0.001
output: ./result
patience_epochs: 10
pin_mem: false
pretrained: false
recount: 1
recovery_interval: 0
redundant_bias: null
remode: pixel
reprob: 0.0
resume: ''
root: ''
save_images: false
sched: cosine
seed: 0
smoothing: null
soft_nms: null
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
tta: 0
val_skip: 0
warmup_epochs: 5
warmup_lr: 0.0001
weight_decay: 4.0e-05
world_size: 1
workers: 4